In [1]:
import numpy as np
import pandas as pd 
from sklearn import preprocessing

In [2]:
df = pd.read_csv(r'C:\Users\ARIO\Documents\16325569497737558.csv')

In [3]:
print(df.head())
print(df.shape)

   age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1  
(303, 14)


In [4]:
df['oldpeak'] = df['oldpeak'].astype(int)
df.oldpeak[0:5]

0    2
1    3
2    1
3    0
4    0
Name: oldpeak, dtype: int64

In [5]:
df['oldpeak'].value_counts()

oldpeak
0    166
1     78
2     34
3     17
4      6
6      1
5      1
Name: count, dtype: int64

In [6]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [27]:
x = df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall']].values
x[0:5]

array([[ 63,   1,   3, 145, 233,   1,   0, 150,   0,   2,   0,   0,   1],
       [ 37,   1,   2, 130, 250,   0,   1, 187,   0,   3,   0,   0,   2],
       [ 41,   0,   1, 130, 204,   0,   0, 172,   0,   1,   2,   0,   2],
       [ 56,   1,   1, 120, 236,   0,   1, 178,   0,   0,   2,   0,   2],
       [ 57,   0,   0, 120, 354,   0,   1, 163,   1,   0,   2,   0,   2]])

In [28]:
y = df[["output"]].values
y[0:5]

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [29]:

scale = preprocessing.StandardScaler().fit(x)
x = scale.transform(x.astype(float))
x [0:2]

array([[ 0.9521966 ,  0.68100522,  1.97312292,  0.76395577, -0.25633371,
         2.394438  , -1.00583187,  0.01544279, -0.69663055,  1.15447496,
        -2.27457861, -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, -0.09273778,  0.07219949,
        -0.41763453,  0.89896224,  1.63347147, -0.69663055,  2.08978489,
        -2.27457861, -0.71442887, -0.51292188]])

In [16]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size=0.2 , random_state=4) 
print('Train',x_train.shape , y_train.shape)
print('Test' , x_test.shape ,y_test.shape )


Train (242, 13) (242, 1)
Test (61, 13) (61, 1)


In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
from sklearn.metrics import confusion_matrix 

In [33]:
LR = LogisticRegression(C=0.01 , solver='liblinear').fit(x_train,y_train)
LR

C:\Users\ARIO\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=0.01, solver='liblinear')

In [34]:
yhat = LR.predict(x_test)
print(y_test[0:5])
print(yhat[0:5])

[[1]
 [0]
 [1]
 [1]
 [0]]
[1 0 1 1 1]


In [35]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob[0:5]

array([[0.38287353, 0.61712647],
       [0.73648664, 0.26351336],
       [0.39161714, 0.60838286],
       [0.19662634, 0.80337366],
       [0.40854713, 0.59145287]])

In [36]:
from sklearn.metrics import jaccard_score 


In [37]:
jaccard_score(y_test,yhat,pos_label=0)

np.float64(0.7407407407407407)